services:
  nginx:
    image: nginxweb
    build: ./nginx
    container_name: nginx
    ports:
      - "443:8086"
    environment:
      - PORT=8086
    networks:
      - mynet
  apache:
    image: apacheweb
    build: ./apache
    container_name: apache
    networks:
      - mynet
  gows:
    image: gows
    build: ./goback
    container_name: gows
    networks:
      - mynet


networks:
  mynet: