services:
  nginx:
    image: nginxweb
    build: ./nginx
    container_name: nginx
    ports:
      - "443:8086"
    environment:
      - PORT=8086
    networks:
      - mynet

  apache:
    image: apacheweb
    build: ./apache
    container_name: apache
    networks:
      - mynet

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
        #- ./postgres/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet


  gows:
    image: gows
    build: ./goback
    container_name: gows
    networks:
      - mynet


networks:
  mynet:
