services:
  nginx:
    image: lelisleonar/nginx:latest 
    ports:
      - "443:8086"
    environment:
      - PORT=8086
    networks:
      - app

  apache:
    image: lelisleonar/apache:latest
    networks:
      - app

networks:
  app:

